const imagesAssetsPrefix = "/assets/images";

export const assetsConstants = {
  logo: `${imagesAssetsPrefix}/global/logo.png`,
  logoWhiteText: `${imagesAssetsPrefix}/global/logo-white-text.png`,
  defaultImage: `${imagesAssetsPrefix}/global/deafult-image.jpg`,
  favouriteIcon: `${imagesAssetsPrefix}/icons/svg/Heart.svg`,
  favouriteRedIcon: `${imagesAssetsPrefix}/icons/svg/red-heart.svg`,
  cartIcon: `${imagesAssetsPrefix}/icons/svg/Buy.svg`,
  categoryPlaceholderIcon: `${imagesAssetsPrefix}/icons/svg/food-supplies.svg`,
  categoriesCountIcon: `${imagesAssetsPrefix}/icons/svg/categories-count.svg`,
  storesCountIcon: `${imagesAssetsPrefix}/icons/svg/stores-count.svg`,
  brandPlaceholderIcon: `${imagesAssetsPrefix}/icons/svg/brand-placeholder.svg`,
  deliveryIcon: `${imagesAssetsPrefix}/icons/svg/delivery.svg`,
  refundIcon: `${imagesAssetsPrefix}/icons/svg/refund.svg`,
  contactIcon: `${imagesAssetsPrefix}/icons/svg/contact.svg`,
  googlePlayIcon: `${imagesAssetsPrefix}/icons/svg/google-play-icon.svg`,
  appStoreIcon: `${imagesAssetsPrefix}/icons/svg/app-store-icon.svg`,
  instagram: `${imagesAssetsPrefix}/icons/svg/instagram.svg`,
  facebook: `${imagesAssetsPrefix}/icons/svg/facebook.svg`,
  twitter: `${imagesAssetsPrefix}/icons/svg/twitter.svg`,
  linkedIn: `${imagesAssetsPrefix}/icons/svg/linked-in.svg`,
  youtube: `${imagesAssetsPrefix}/icons/svg/youtube.svg`,
  dribbble: `${imagesAssetsPrefix}/icons/svg/dribbble.svg`,
  bannerPlaceholder: `${imagesAssetsPrefix}/global/banner.png`,
  addToCartIcon: `${imagesAssetsPrefix}/icons/svg/cart.svg`,
  libyaFlagIcon: `${imagesAssetsPrefix}/icons/svg/libya-flag.svg`,
  englishFlagIcon: `${imagesAssetsPrefix}/icons/svg/uk-flag.svg`,
  yousrPayIcon: `${imagesAssetsPrefix}/icons/svg/yousr-pay.svg`,
  bankCardIcon: `${imagesAssetsPrefix}/icons/svg/bank-card.svg`,
  walletIcon: `${imagesAssetsPrefix}/icons/svg/wallet.svg`,
  payOnDeliveryIcon: `${imagesAssetsPrefix}/icons/svg/pay-on-delivery.svg`,
  filterIcon: `${imagesAssetsPrefix}/icons/svg/filter.svg`,
  addToCartIllustration: `${imagesAssetsPrefix}/global/add-to-cart-illustration.png`,
  mainDecor: `${imagesAssetsPrefix}/global/main-decor.png`,
  footerBackground: `${imagesAssetsPrefix}/global/footer-background.jpg`,
};
